### ISSUE TITLE
This code is not able to typing text in the email field

### ISSUE THREAD

**Issue by ThrishnaReghuram** [tabhresh/Edureka_23July#1]
package module1;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class FirstJava {

	public static void main(String[] args) {
		System.setProperty("webdriver.chrome.driver", "C:\\Users\\Himaja\\Downloads\\SeleniumProject\\Training\\drivers\\chromedriver.exe");
		WebDriver driver= new ChromeDriver();
		
		driver.get("https://www.facebook.com");
		
		driver.findElement(By.id("email")).sendKeys("Thrishna");
		driver.close();
	}

}

**Comment by Swetharegintala** [comment]
This could be due to page load is not complete, before the selenium trying to find the email field.
Please use wait command, before findElement.

**Comment by DhirajBarhate** [comment]
The issue is your chrome driver path is not proper & please comment "driver.close();"

Following is the working code

package module1;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class Sample {

public static void main(String[] args) {
	System.setProperty("webdriver.chrome.driver", "chromedriver");
	WebDriver driver= new ChromeDriver();
	
	driver.get("https://www.facebook.com");
	
	driver.findElement(By.id("email")).sendKeys("Dhiraj");
	//driver.close();
}
}

**Comment by tabhresh** [comment]
Hi Trishna,

You code is working into my system only missing was the last curly braces rest is fine in my case. Pls post ur console error msg that will help us more!
